version: '3'
services:
  flask:
    build: 
      context: .
      dockerfile: ./flask/Dockerfile
    image: flask_img
    container_name: flask_container
    tty: true
    volumes:
      - ./flask:/usr/src/app
    ports:
      - "9000:80"
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./jupyter_notebook/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''